version: '3'
services:
  router:
    image: alpine
    container_name: router1
    cap_add:
      - NET_ADMIN
    networks:
      net1:
        ipv6_address: 2001:db8:1001::1
      net2:
        ipv6_address: 2001:db8:1002::1

  pc1:
    image: alpine
    container_name: pc1
    cap_add:
      - NET_ADMIN
    networks:
      net1:
        ipv6_address: 2001:db8:1001::2

  pc2:
    image: alpine
    container_name: pc2
    cap_add:
      - NET_ADMIN
    networks:
      net2:
        ipv6_address: 2001:db8:1002::2

networks:
  net1:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 2001:db8:1001::/64

  net2:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 2001:db8:1002::/64
